FROM node:23-alpine3.20

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install -g pnpm
RUN pnpm install

EXPOSE 4001

CMD ["pnpm","dev"]